# Generated by Django 4.2.6 on 2023-10-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_banner',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='college_logo',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
