# Generated by Django 4.2.6 on 2023-10-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_colleneg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='colleneg_name',
            new_name='college_name',
        ),
    ]
